/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calibration/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calibration Next */
        post: operations["getNextCalibrationTrial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calibration/response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calibration Response */
        post: operations["submitCalibrationResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Matches Rank */
        post: operations["rankMatches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/measurement/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Measurement Next */
        post: operations["getNextMeasurementItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/measurement/response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Measurement Response */
        post: operations["submitMeasurementResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/measurement/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Measurement Score */
        post: operations["scoreMeasurementSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/synthetic-calibration/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synthetic Calibration Next */
        post: operations["getNextSyntheticCalibrationPair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/synthetic-calibration/response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synthetic Calibration Response */
        post: operations["submitSyntheticCalibrationResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalibrationNextRequest */
        CalibrationNextRequest: Record<string, never>;
        /** CalibrationNextResponse */
        CalibrationNextResponse: {
            /** Completed Trial Count */
            completed_trial_count: number;
            /** Experiment Id */
            experiment_id?: string | null;
            /** Instrument Version */
            instrument_version: string;
            /**
             * Is Mock
             * @default true
             * @constant
             */
            is_mock: true;
            /** Ordinal */
            ordinal?: number | null;
            /** Policy Version */
            policy_version: string;
            /** Response Options */
            response_options?: components["schemas"]["CalibrationResponseChoice"][];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["CalibrationNextStatus"];
            stimulus?: components["schemas"]["CalibrationStimulus"] | null;
            /** Stimulus Id */
            stimulus_id?: string | null;
            /** Stimulus Version */
            stimulus_version?: string | null;
            /** Target Trial Count */
            target_trial_count: number;
        };
        /**
         * CalibrationNextStatus
         * @enum {string}
         */
        CalibrationNextStatus: "trial" | "complete";
        /**
         * CalibrationResponseChoice
         * @enum {string}
         */
        CalibrationResponseChoice: "left" | "right" | "both" | "neither";
        /** CalibrationResponseReceipt */
        CalibrationResponseReceipt: {
            /**
             * Accepted
             * @default true
             * @constant
             */
            accepted: true;
            /**
             * Client Response Id
             * Format: uuid
             */
            client_response_id: string;
            /** Completed Trial Count */
            completed_trial_count: number;
            /** Duplicate */
            duplicate: boolean;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Is Mock
             * @default true
             * @constant
             */
            is_mock: true;
            /** Policy Version */
            policy_version: string;
            /**
             * Server Timestamp
             * Format: date-time
             */
            server_timestamp: string;
            /** Session Complete */
            session_complete: boolean;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Target Trial Count */
            target_trial_count: number;
        };
        /** CalibrationResponseRequest */
        CalibrationResponseRequest: {
            /**
             * Client Response Id
             * Format: uuid
             */
            client_response_id: string;
            /** Client Timestamp */
            client_timestamp?: string | null;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            response: components["schemas"]["CalibrationResponseChoice"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** CalibrationStimulus */
        CalibrationStimulus: {
            /**
             * Kind
             * @default text_pair
             * @constant
             */
            kind: "text_pair";
            left: components["schemas"]["CalibrationStimulusOption"];
            right: components["schemas"]["CalibrationStimulusOption"];
        };
        /** CalibrationStimulusOption */
        CalibrationStimulusOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** ForcedChoiceItem */
        ForcedChoiceItem: {
            /** Dimension Key */
            dimension_key: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "forced_choice";
            left: components["schemas"]["MeasurementChoiceOption"];
            /** Prompt */
            prompt: string;
            right: components["schemas"]["MeasurementChoiceOption"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HardConstraintItem */
        HardConstraintItem: {
            /** Dimension Key */
            dimension_key: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "hard_constraint";
            /** Options */
            options: components["schemas"]["MeasurementChoiceOption"][];
            /** Prompt */
            prompt: string;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** MatchRankRequest */
        MatchRankRequest: {
            /** Candidate Ids */
            candidate_ids: string[];
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** MeasurementChoiceAnswer */
        MeasurementChoiceAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "choice";
            /** Option Id */
            option_id: string;
        };
        /** MeasurementChoiceOption */
        MeasurementChoiceOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** MeasurementNextRequest */
        MeasurementNextRequest: Record<string, never>;
        /** MeasurementNextResponse */
        MeasurementNextResponse: {
            /** Completed Item Count */
            completed_item_count: number;
            /** Instrument Key */
            instrument_key: string;
            /** Instrument Version */
            instrument_version: string;
            /**
             * Is Mock
             * @default true
             * @constant
             */
            is_mock: true;
            /** Item */
            item?: (components["schemas"]["HardConstraintItem"] | components["schemas"]["RatingItem"] | components["schemas"]["ScenarioItem"] | components["schemas"]["ForcedChoiceItem"]) | null;
            /** Item Id */
            item_id?: string | null;
            /** Item Version */
            item_version?: string | null;
            /** Ordinal */
            ordinal?: number | null;
            /** Presentation Id */
            presentation_id?: string | null;
            /** Selection Policy Version */
            selection_policy_version: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["MeasurementNextStatus"];
            /** Target Item Count */
            target_item_count: number;
        };
        /**
         * MeasurementNextStatus
         * @enum {string}
         */
        MeasurementNextStatus: "item" | "complete";
        /** MeasurementRatingAnswer */
        MeasurementRatingAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rating";
            /** Value */
            value: number;
        };
        /** MeasurementResponseReceipt */
        MeasurementResponseReceipt: {
            /**
             * Accepted
             * @default true
             * @constant
             */
            accepted: true;
            /**
             * Client Response Id
             * Format: uuid
             */
            client_response_id: string;
            /** Completed Item Count */
            completed_item_count: number;
            /** Duplicate */
            duplicate: boolean;
            /** Instrument Version */
            instrument_version: string;
            /**
             * Is Mock
             * @default true
             * @constant
             */
            is_mock: true;
            /**
             * Presentation Id
             * Format: uuid
             */
            presentation_id: string;
            /** Selection Policy Version */
            selection_policy_version: string;
            /**
             * Server Timestamp
             * Format: date-time
             */
            server_timestamp: string;
            /** Session Complete */
            session_complete: boolean;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Target Item Count */
            target_item_count: number;
        };
        /** MeasurementResponseRequest */
        MeasurementResponseRequest: {
            /** Answer */
            answer: components["schemas"]["MeasurementChoiceAnswer"] | components["schemas"]["MeasurementRatingAnswer"];
            /**
             * Client Response Id
             * Format: uuid
             */
            client_response_id: string;
            /** Client Timestamp */
            client_timestamp?: string | null;
            /**
             * Presentation Id
             * Format: uuid
             */
            presentation_id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** MeasurementScoreRequest */
        MeasurementScoreRequest: {
            scoring_version: components["schemas"]["MeasurementScoringVersion"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** MeasurementScoreResponse */
        MeasurementScoreResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence Fingerprint */
            evidence_fingerprint: string;
            /**
             * Is Mock
             * @default true
             * @constant
             */
            is_mock: true;
            /** Response Count */
            response_count: number;
            /**
             * Score Run Id
             * Format: uuid
             */
            score_run_id: string;
            /** Scores */
            scores: {
                [key: string]: number;
            };
            scoring_version: components["schemas"]["MeasurementScoringVersion"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /**
         * MeasurementScoringVersion
         * @enum {string}
         */
        MeasurementScoringVersion: "mock-measurement-p5-score-1.0.0" | "mock-measurement-p5-score-2.0.0";
        /** PersistedMatchRankResponse */
        PersistedMatchRankResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Is Mock
             * @default true
             * @constant
             */
            is_mock: true;
            /** Model Version */
            model_version: string;
            /**
             * Persisted
             * @default true
             * @constant
             */
            persisted: true;
            /** Ranked Candidates */
            ranked_candidates: components["schemas"]["RankedCandidate"][];
            /** Request Fingerprint */
            request_fingerprint: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** RankedCandidate */
        RankedCandidate: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Rank */
            rank: number;
            /** Rank Score */
            rank_score: number;
        };
        /** RatingItem */
        RatingItem: {
            /** Dimension Key */
            dimension_key: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rating";
            /** Max Label */
            max_label: string;
            /** Min Label */
            min_label: string;
            /** Prompt */
            prompt: string;
            /**
             * Scale Max
             * @default 5
             */
            scale_max: number;
            /**
             * Scale Min
             * @default 1
             */
            scale_min: number;
        };
        /** ScenarioItem */
        ScenarioItem: {
            /** Dimension Key */
            dimension_key: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "scenario";
            /** Options */
            options: components["schemas"]["MeasurementChoiceOption"][];
            /** Prompt */
            prompt: string;
        };
        /** SyntheticAsset */
        SyntheticAsset: {
            /**
             * Asset Id
             * Format: uuid
             */
            asset_id: string;
            /** Asset Uri */
            asset_uri: string;
            /** Content Sha256 */
            content_sha256: string;
            /** Media Type */
            media_type: string;
            provenance: components["schemas"]["SyntheticGenerationProvenance"];
            /**
             * Specification Id
             * Format: uuid
             */
            specification_id: string;
        };
        /** SyntheticCalibrationNextRequest */
        SyntheticCalibrationNextRequest: Record<string, never>;
        /** SyntheticCalibrationNextResponse */
        SyntheticCalibrationNextResponse: {
            /** Cache Ready */
            cache_ready: boolean;
            /** Completed Trial Count */
            completed_trial_count: number;
            /** Generator Adapter Version */
            generator_adapter_version: string;
            /** Instrument Version */
            instrument_version: string;
            /**
             * Is Mock
             * @default true
             * @constant
             */
            is_mock: true;
            pair?: components["schemas"]["SyntheticCalibrationPair"] | null;
            /** Pair Policy Version */
            pair_policy_version: string;
            /** Response Options */
            response_options?: components["schemas"]["CalibrationResponseChoice"][];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["SyntheticCalibrationNextStatus"];
            /** Target Trial Count */
            target_trial_count: number;
        };
        /**
         * SyntheticCalibrationNextStatus
         * @enum {string}
         */
        SyntheticCalibrationNextStatus: "pair" | "complete";
        /** SyntheticCalibrationPair */
        SyntheticCalibrationPair: {
            left: components["schemas"]["SyntheticAsset"];
            /** Ordinal */
            ordinal: number;
            /**
             * Pair Id
             * Format: uuid
             */
            pair_id: string;
            /** Pair Policy Version */
            pair_policy_version: string;
            /** Randomization Seed */
            randomization_seed: number;
            right: components["schemas"]["SyntheticAsset"];
        };
        /** SyntheticCalibrationResponseReceipt */
        SyntheticCalibrationResponseReceipt: {
            /**
             * Accepted
             * @default true
             * @constant
             */
            accepted: true;
            /**
             * Client Response Id
             * Format: uuid
             */
            client_response_id: string;
            /** Completed Trial Count */
            completed_trial_count: number;
            /** Duplicate */
            duplicate: boolean;
            /**
             * Is Mock
             * @default true
             * @constant
             */
            is_mock: true;
            /**
             * Pair Id
             * Format: uuid
             */
            pair_id: string;
            /** Pair Policy Version */
            pair_policy_version: string;
            /**
             * Server Timestamp
             * Format: date-time
             */
            server_timestamp: string;
            /** Session Complete */
            session_complete: boolean;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Target Trial Count */
            target_trial_count: number;
        };
        /** SyntheticCalibrationResponseRequest */
        SyntheticCalibrationResponseRequest: {
            /**
             * Client Response Id
             * Format: uuid
             */
            client_response_id: string;
            /** Client Timestamp */
            client_timestamp?: string | null;
            /**
             * Pair Id
             * Format: uuid
             */
            pair_id: string;
            response: components["schemas"]["CalibrationResponseChoice"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** SyntheticGenerationProvenance */
        SyntheticGenerationProvenance: {
            /** Adapter Key */
            adapter_key: string;
            /** Adapter Version */
            adapter_version: string;
            /** Model */
            model: string;
            /** Model Revision */
            model_revision: string;
            /** Parameters */
            parameters: {
                [key: string]: string | number | boolean;
            };
            /** Prompt */
            prompt: string;
            /** Provider */
            provider: string;
            /** Seed */
            seed: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Api Version */
            api_version: string;
            /** Calibration Policy Version */
            calibration_policy_version: string;
            /** Contract Version */
            contract_version: string;
            /** Engine Version */
            engine_version: string;
            /** Ranker Model Version */
            ranker_model_version: string;
            /** Service */
            service: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getNextCalibrationTrial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationNextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationNextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitCalibrationResponse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationResponseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationResponseReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rankMatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRankRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersistedMatchRankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getNextMeasurementItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasurementNextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementNextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitMeasurementResponse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasurementResponseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementResponseReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scoreMeasurementSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeasurementScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeasurementScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getNextSyntheticCalibrationPair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyntheticCalibrationNextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyntheticCalibrationNextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitSyntheticCalibrationResponse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyntheticCalibrationResponseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyntheticCalibrationResponseReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
