/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calibration/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calibration Next */
        post: operations["getNextCalibrationTrial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calibration/response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Calibration Response */
        post: operations["submitCalibrationResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Matches Rank */
        post: operations["rankMatches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CalibrationNextRequest */
        CalibrationNextRequest: {
            /** Completed Trial Count */
            completed_trial_count: number;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** CalibrationNextResponse */
        CalibrationNextResponse: {
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Is Mock
             * @default true
             * @constant
             */
            is_mock: true;
            /** Ordinal */
            ordinal: number;
            /** Policy Version */
            policy_version: string;
            /** Response Options */
            response_options: components["schemas"]["CalibrationResponseChoice"][];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            stimulus: components["schemas"]["CalibrationStimulus"];
        };
        /**
         * CalibrationResponseChoice
         * @enum {string}
         */
        CalibrationResponseChoice: "left" | "right" | "both" | "neither";
        /** CalibrationResponseReceipt */
        CalibrationResponseReceipt: {
            /**
             * Accepted
             * @default true
             * @constant
             */
            accepted: true;
            /**
             * Client Response Id
             * Format: uuid
             */
            client_response_id: string;
            /**
             * Duplicate
             * @default false
             * @constant
             */
            duplicate: false;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            /**
             * Is Mock
             * @default true
             * @constant
             */
            is_mock: true;
            /** Policy Version */
            policy_version: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** CalibrationResponseRequest */
        CalibrationResponseRequest: {
            /**
             * Client Response Id
             * Format: uuid
             */
            client_response_id: string;
            /** Client Timestamp */
            client_timestamp?: string | null;
            /**
             * Experiment Id
             * Format: uuid
             */
            experiment_id: string;
            response: components["schemas"]["CalibrationResponseChoice"];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** CalibrationStimulus */
        CalibrationStimulus: {
            /**
             * Kind
             * @default text_pair
             * @constant
             */
            kind: "text_pair";
            left: components["schemas"]["CalibrationStimulusOption"];
            right: components["schemas"]["CalibrationStimulusOption"];
        };
        /** CalibrationStimulusOption */
        CalibrationStimulusOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Service */
            service: string;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** MatchRankRequest */
        MatchRankRequest: {
            /** Candidate Ids */
            candidate_ids: string[];
            /**
             * Limit
             * @default 10
             */
            limit: number;
        };
        /** MatchRankResponse */
        MatchRankResponse: {
            /**
             * Is Mock
             * @default true
             * @constant
             */
            is_mock: true;
            /** Model Version */
            model_version: string;
            /** Ranked Candidates */
            ranked_candidates: components["schemas"]["RankedCandidate"][];
        };
        /** RankedCandidate */
        RankedCandidate: {
            /**
             * Candidate Id
             * Format: uuid
             */
            candidate_id: string;
            /** Rank */
            rank: number;
            /** Rank Score */
            rank_score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VersionResponse */
        VersionResponse: {
            /** Api Version */
            api_version: string;
            /** Calibration Policy Version */
            calibration_policy_version: string;
            /** Contract Version */
            contract_version: string;
            /** Engine Version */
            engine_version: string;
            /** Ranker Model Version */
            ranker_model_version: string;
            /** Service */
            service: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getNextCalibrationTrial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationNextRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationNextResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submitCalibrationResponse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalibrationResponseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationResponseReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rankMatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRankRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchRankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
        };
    };
}
