import type { components } from './generated';

export type { components, operations, paths } from './generated';

export type HealthResponse = components['schemas']['HealthResponse'];
export type VersionResponse = components['schemas']['VersionResponse'];
export type CalibrationResponseChoice = components['schemas']['CalibrationResponseChoice'];
export type CalibrationNextStatus = components['schemas']['CalibrationNextStatus'];
export type CalibrationNextRequest = components['schemas']['CalibrationNextRequest'];
export type CalibrationNextResponse = components['schemas']['CalibrationNextResponse'];
export type CalibrationResponseRequest = components['schemas']['CalibrationResponseRequest'];
export type CalibrationResponseReceipt = components['schemas']['CalibrationResponseReceipt'];
export type MeasurementNextStatus = components['schemas']['MeasurementNextStatus'];
export type MeasurementNextRequest = components['schemas']['MeasurementNextRequest'];
export type MeasurementNextResponse = components['schemas']['MeasurementNextResponse'];
export type MeasurementResponseRequest = components['schemas']['MeasurementResponseRequest'];
export type MeasurementResponseReceipt = components['schemas']['MeasurementResponseReceipt'];
export type MeasurementScoreRequest = components['schemas']['MeasurementScoreRequest'];
export type MeasurementScoreResponse = components['schemas']['MeasurementScoreResponse'];
export type MeasurementScoringVersion = components['schemas']['MeasurementScoringVersion'];
export type MeasurementChoiceOption = components['schemas']['MeasurementChoiceOption'];
export type HardConstraintItem = components['schemas']['HardConstraintItem'];
export type RatingItem = components['schemas']['RatingItem'];
export type ScenarioItem = components['schemas']['ScenarioItem'];
export type ForcedChoiceItem = components['schemas']['ForcedChoiceItem'];
export type MeasurementChoiceAnswer = components['schemas']['MeasurementChoiceAnswer'];
export type MeasurementRatingAnswer = components['schemas']['MeasurementRatingAnswer'];
export type SyntheticCalibrationNextStatus = components['schemas']['SyntheticCalibrationNextStatus'];
export type SyntheticCalibrationNextRequest = components['schemas']['SyntheticCalibrationNextRequest'];
export type SyntheticCalibrationNextResponse = components['schemas']['SyntheticCalibrationNextResponse'];
export type SyntheticCalibrationResponseRequest = components['schemas']['SyntheticCalibrationResponseRequest'];
export type SyntheticCalibrationResponseReceipt = components['schemas']['SyntheticCalibrationResponseReceipt'];
export type SyntheticCalibrationPair = components['schemas']['SyntheticCalibrationPair'];
export type SyntheticAsset = components['schemas']['SyntheticAsset'];
export type SyntheticGenerationProvenance = components['schemas']['SyntheticGenerationProvenance'];
export type MatchRankRequest = components['schemas']['MatchRankRequest'];
export type PersistedMatchRankResponse = components['schemas']['PersistedMatchRankResponse'];
